#!/bin/bash


if [ `whoami` != root ]; then
	echo Run as root
	exit
fi

set -e

ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime

apt-get --yes --force-yes update

apt-get --yes --force-yes install tmux vim git
apt-get --yes --force-yes install python2.7 python-pip
pip install ipython pip

# WARNING! Your environment specifies an invalid locale.
apt-get --yes --force-yes install language-pack-en
