#!/bin/bash
if [ `whoami` != root ]; then
	echo Run as root
	exit 5
fi

# Run against raspbian jessie
# NOTE use raspi-config for other things

# exit on error
#set -e

ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
# debian/ubuntu
apt-get --yes --force-yes update || exit 2

# textmode
apt-get --yes --force-yes install picocom vim ssh figlet build-essential \
	bash-completion keychain htop curl tree sox socat netcat nmap p7zip-full \
	fish nodejs git tmux npm python-pip

# Make node processes able to listen on port 80
# http://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-1024-on-l
apt-get --yes --force-yes install libcap2-bin
setcap 'cap_net_bind_service=+ep' /usr/bin/nodejs

if ! grep usb_max_current /boot/config.txt; then
	echo 'usb_max_current=1' >> /boot/config.txt
	#echo 'gpu_mem=16' >> /boot/config.txt
fi
