#!/bin/bash
if [ `whoami` != root ]; then
	echo Run as root
	exit 5
fi

# exit on error
set -e

ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
# debian/ubuntu
apt-get --yes --force-yes update || exit 2

# textmode
apt-get --yes --force-yes install picocom vim ssh figlet build-essential \
	bash-completion keychain htop curl tree sox socat netcat nmap p7zip-full

# these are PPAs in 12.04
apt-get --yes --force-yes install fish nodejs git


# From raspi-config https://github.com/asb/raspi-config/blob/master/raspi-config
if ! [ -h /dev/root ]; then
	echo "/dev/root does not exist or is not a symlink. Don't know how to expand" 20 60 2
	exit 0
fi

ROOT_PART=$(readlink /dev/root)
PART_NUM=${ROOT_PART#mmcblk0p}
if [ "$PART_NUM" = "$ROOT_PART" ]; then
	echo "/dev/root is not an SD card. Don't know how to expand" 20 60 2
	exit 0
fi

# NOTE: the NOOBS partition layout confuses parted. For now, let's only 
# agree to work with a sufficiently simple partition layout
if [ "$PART_NUM" -ne 2 ]; then
	echo "Your partition layout is not currently supported by this tool. You are probably using NOOBS, in which case your root filesystem is already expanded anyway." 20 60 2
	exit 0
fi

LAST_PART_NUM=$(parted /dev/mmcblk0 -ms unit s p | tail -n 1 | cut -f 1 -d:)

if [ "$LAST_PART_NUM" != "$PART_NUM" ]; then
	echo "/dev/root is not the last partition. Don't know how to expand" 20 60 2
	exit 0
fi

# Get the starting offset of the root partition
PART_START=$(parted /dev/mmcblk0 -ms unit s p | grep "^${PART_NUM}" | cut -f 2 -d:)
[ "$PART_START" ] || exit 1
# Return value will likely be error for fdisk as it fails to reload the
# partition table because the root fs is mounted
fdisk /dev/mmcblk0 <<EOF
p
d
$PART_NUM
n
p
$PART_NUM
$PART_START

p
w
EOF

# now set up an init.d script
cat <<\EOF > /etc/init.d/resize2fs_once &&
#!/bin/sh
### BEGIN INIT INFO
# Provides:          resize2fs_once
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5 S
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting resize2fs_once" &&
    resize2fs /dev/root &&
    rm /etc/init.d/resize2fs_once &&
    update-rc.d resize2fs_once remove &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
EOF

chmod +x /etc/init.d/resize2fs_once &&
update-rc.d resize2fs_once defaults &&
if [ "$INTERACTIVE" = True ]; then
	echo "Root partition has been resized.\nThe filesystem will be enlarged upon the next reboot"
fi


# Make node processes able to listen on port 80
# http://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-1024-on-l
apt-get --yes --force-yes install libcap2-bin
setcap 'cap_net_bind_service=+ep' /usr/bin/nodejs

# tmux 1.9a
apt-get --yes --force-yes install libncurses-dev
pushd /tmp/
	wget "https://github.com/downloads/libevent/libevent/libevent-2.0.21-stable.tar.gz"
	tar -xf libevent-2.0.21-stable.tar.gz
	pushd libevent-2.0.21-stable
		./configure
		make
		sudo make install
		sudo ldconfig
	popd

	wget "http://downloads.sourceforge.net/project/tmux/tmux/tmux-1.9/tmux-1.9a.tar.gz"
	tar -xf tmux-1.9a.tar.gz
	pushd tmux-1.9a/
		./configure
		make
		sudo make install
	popd
popd

