#!/bin/bash

if [ `whoami` != root ]; then
	echo Run as root
	exit
fi

# echo commands to aid debugging
set -x

ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
# debian/ubuntu

export SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# a lot of packages live here
add-apt-repository universe
add-apt-repository multiverse

apt-add-repository --yes ppa:numix/ppa

apt-get update || exit 2

locale-gen en_GB.UTF-8
sudo update-locale LANG=en_GB.UTF-8 lANGUAGE=en_GB.UTF-8 lC_ALL=en_GB.UTF-8

# textmode
# theme stuff
apt-get --yes --force-yes install numix-gtk-theme
# numix-icon-theme is good but I prefer regular desaturated ubuntu icons

# gui
apt-get --yes --force-yes install chromium-browser vlc
apt-get --yes --force-yes remove --purge firefox 'ubuntuone-*' ssh-askpass-gnome


# removed advert apps
rm /usr/share/applications/*amazon*
rm /usr/share/applications/*ubuntuone*
rm /usr/share/applications/UbuntuOneMusiconeubuntucom.desktop

# remove amazon searching...
# still works in chroot for livecd if HOME is /etc/skel
dbus-launch gsettings set com.canonical.Unity.Lenses remote-content-search none
# background

# run  gsettings list-recursively > gsettings.txt before and after making changes with gui, then diff. Results:
dbus-launch gsettings set org.gnome.desktop.screensaver lock-enabled false
dbus-launch gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false
dbus-launch gsettings set org.gnome.desktop.privacy remember-recent-files false
dbus-launch gsettings set org.gnome.desktop.session idle-delay 0 # do not turn off screen after delay
dbus-launch gsettings set com.canonical.Unity.Launcher favorites "['application://nautilus.desktop',
	'application://gnome-control-center.desktop', 'unity://running-apps',
	'application://gnome-system-monitor.desktop', 'application://chromium-browser.desktop',
	'application://debian-xterm.desktop', 'unity://expo-icon', 'unity://devices']"

# move to provision
dbus-launch gsettings set org.gnome.desktop.wm.preferences theme 'Numix'
dbus-launch gsettings set org.gnome.desktop.interface gtk-theme 'Numix'
#dbus-launch gsettings set org.gnome.desktop.interface icon-theme 'Numix'
dbus-launch gsettings set org.gnome.desktop.background primary-color '#000000'
dbus-launch gsettings set org.gnome.desktop.background secondary-color '#000000'
dbus-launch gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/xgu472hf2_by_lariliikala.jpg'

# xterm maximized always
#sed -ir 's/Exec=xterm$/Exec=xterm -maximized/g' /usr/share/applications/debian-xterm.desktop

# fix unmet deps caused by removing stuff
apt-get --yes --force-yes -f install

# orphaned packages
apt-get --yes --force-yes autoremove

# note apt-get upgrade can cause problems. Don't do it when building a livecd.

# desaturate!
$SCRIPT_DIR/desaturate_ubuntu.py
