#! /bin/sh


# suggestion: in xinitrc also launch a panel such as mate-panel, lemonboy bar
# or tint2. Lemonboy bar does not have mouse control.

bspc config border_width        2
bspc config window_gap         42

bspc config split_ratio         0.62
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d ALPHA BETA CHARLIE DELTA ECHO

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
