#! /bin/bash

git config --global user.name 'jimjibone'
git config --global user.email 'jamesreuss@gmail.com'

# personal settings for bash
echo "alias la='ls -a'" >> ~/.bashrc
echo 'export CLICOLOR=1' >> ~/.bashrc
#light echo 'export LSCOLORS=ExFxCxDxBxegedabagacad' >> ~/.bashrc
echo 'export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx' >> ~/.bashrc

# initial mac setup is now done by prerequisites/osx.sh
