#! /bin/bash

git config --global user.name 'jimjibone'
git config --global user.email 'jamesreuss@gmail.com'

# personal settings for bash
echo "alias la='ls -a'" >> ~/.bashrc
echo 'export CLICOLOR=1' >> ~/.bashrc
#light echo 'export LSCOLORS=ExFxCxDxBxegedabagacad' >> ~/.bashrc
echo 'export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx' >> ~/.bashrc

#initial mac setup
if [[ `uname` == 'Darwin' ]]; then
	# disable warning when changing file extensions
	defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
	# enable disk utility debug menu
	defaults write com.apple.DiskUtility DUDebugMenuEnabled -bool true
	# enable text selection in quick look
	defaults write com.apple.finder QLEnableTextSelection -boolean YES
	# disable dashboard because it sucks
	defaults write com.apple.dashboard mcx-disabled -boolean YES
	# make the user library folder visible again
	chflags no hidden ~/Library/
	# refresh stuff
	killall Dock
	killall Finder
fi
