#! /bin/bash

git config --global user.name 'jimjibone'
git config --global user.email 'jamesreuss@gmail.com'

# personal settings for bash
text="alias la='ls -a';\
export CLICOLOR=1;\
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx;"
#light screen 'export LSCOLORS=ExFxCxDxBxegedabagacad'

# prepend the 'text' onto .bashrc
exec 3<> ~/.bashrc && awk -v TEXT="$text" 'BEGIN {print TEXT}{print}' ~/.bashrc >&3
