#!/bin/bash

# initial mac setup

# disable warning when changing file extensions
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# enable disk utility debug menu
defaults write com.apple.DiskUtility DUDebugMenuEnabled -bool true

# enable text selection in quick look
defaults write com.apple.finder QLEnableTextSelection -boolean YES

# disable dashboard because it sucks
defaults write com.apple.dashboard mcx-disabled -boolean YES

# make the user library folder visible again
chflags nohidden ~/Library/

# stop preview from opening every PDF you've ever opened every time you view a PDF
# (how did apple think this was a good idea!?!?!)
defaults write com.apple.Preview NSQuitAlwaysKeepsWindows -bool false

# refresh stuff
killall Dock
killall Finder

# install xcode and xcode cli tools (large) or xcode cli tools (small)
# https://developer.apple.com/downloads/index.action

# install homebrew
test -x /usr/local/bin/brew || ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"

brew update || exit 2
brew upgrade

# cli apps
brew install git tmux keychain picocom mcabber htop-osx nodejs autossh bash-completion gnu-sed coreutils ssh-copy-id mpd ncmpcpp mpc fish

# gui apps
brew tap phinze/homebrew-cask
brew install brew-cask
brew cask install google-chrome adium arduino bettertouchtool cyberduck gimp iterm2 macvim virtualbox vlc

# iterm2 prefs
cp etc/com.googlecode.iterm2.plist ~/Library/Preferences/

# set default shell
if ! grep -q /usr/local/bin/fish /etc/shells; then
	echo Registering fish shell...
	echo /usr/local/bin/fish | sudo tee -a /etc/shells
fi
chsh -s /usr/local/bin/fish

# update completion db from man pages. OMGWOW.
/usr/local/bin/fish -c fish_update_completions


