set backspace=indent,eol,start
syntax on
set number
set smartcase
set autoindent
set incsearch

set hlsearch
nnoremap <silent> <CR> :noh<CR><CR>  " Clear search highlight by hitting ente

set cursorline " Highlight current line
set autoread " Reload files that have changed

filetype on
au BufNewFile,BufRead *.less set filetype=css
au BufNewFile,BufRead *.json set filetype=js

set noswapfile

" Nice command. Probably better as a keybinding
" :autocmd BufWritePost * !forever restartall
map <silent> <f5> :!forever restartall <cr>
" map <f5> :autocmd BufWritePost * !forever restartall