#!/usr/bin/env bash
exit 0
function lights {
    http --ignore-stdin --form PUT http://10.171.10.139/api/relay/0 apikey=notsecret value=$1
}

function streaming {
    fuser /dev/video0 &> /dev/null
}

export DSPA_SERVER_HOST=localhost

while sleep 1; do
    while ! streaming; do sleep 1; done
    /home/naggie/dspa7/dist/dspa-announce Cal has joined a meeting
    lights 1
    sleep 600  # stop video testing causing many messages
    while streaming; do sleep 1; done
    /home/naggie/dspa7/dist/dspa-announce "Cal's meeting has finished"
    lights 0
done
