#!/usr/bin/env bash
function lights {
    http --ignore-stdin --form PUT http://10.171.10.139/api/relay/0 apikey=notsecret value=$1
}

function streaming {
    fuser /dev/video0 &> /dev/null
}

while sleep 1; do
    while ! streaming; do sleep 1; done
    lights 1
    while streaming; do sleep 1; done
    lights 0
done
