#!/bin/bash

# clear screen
echo -ne  "\033c"

# white
echo -ne "\033[37m"

# ascii art hostname
hostname -s | tr a-z A-Z | figlet

echo -n "     ."

# domain name
hostname -d | tr a-z A-Z
echo


if [ -r /etc/quotes ]; then
	cat /etc/quotes | sort -R | tail -n 1
	echo
fi

# reset colours
echo -ne "\033[0m"


echo ---
