#!/bin/sh

# clear screen
echo -ne  "\033c"

# red
echo -ne "\033[31m"

# ascii art hostname
hostname -s | tr a-z A-Z | figlet

# white
echo -ne "\033[37m"

# domain name
echo -n "     ."
hostname -d | tr a-z A-Z
echo

# reset
echo -ne "\033[0m"
