#!/bin/bash

# clear screen
echo -ne  "\033c"

# white
echo -ne "\033[37m"

# ascii art hostname
hostname -s | tr a-z A-Z | figlet

# reset colours
echo -ne "\033[0m"

echo -n "Serving "

# white
echo -ne "\033[37m"

# domain name
hostname -d | tr a-z A-Z
echo

# reset colours
echo -ne "\033[0m"

if [ -r /etc/quotes ]; then
	cat /etc/quotes | sort -R | tail -n 1
	echo
fi

