#!/usr/bin/env python
"""
Edits history to deduplicate, leaving the last occurrence of each command.
Filters useless entries. Also normalises whitespace.

To install, add this to .bashrc:

    trap "~/.local/bin/cleanup-history ~/.bash_history" EXIT

"""
from sys import argv
import re
import tempfile
from os import path
from os import rename
from sys import exit

history_file = argv[1]

# new environments won't have the history file yet, it's not a problem
if not path.isfile(history_file):
    exit(0)


SENSITIVE_FRAGMENTS = ['API', 'TOKEN', 'KEY', 'SECRET', 'PASS']

# regexes to ignore
# an alternative to histignore. Processing here means the history will persist
# until the next session ends, which is handy for correcting otherwise ignored
# commands. Also it applies to zsh and bash at the same time.
ignore = [
    # short things
    r"^.{1,3}$",
    # changing into relative directories
    "^cd [^\~/]",
    # taskwarrior operations (+ alias)
    r"^task(?! context)",
    r"^n ",
    r"^week",
    r"^day",
    # yubikey OTP in case it's not disabled or removed
    r"^cccccc",
    r"^ls",
    # annoying if accidentally re-executed at a later date
    r"^git.+--amend",
    r"reboot",
    r"halt",
    # mouse esc codes
    r"^0",
    # commands explicitly hidden by user
    r"^ ",
    # frequent typos (see .aliases)
    r"^git psuh",
    r"^cim ",
    r"^sl ",
    r"^c ",
    r"^xs ",
    r"^cim ",
    r"^bim ",
    r"^nom ",
    r"^gi ",
    r"^cd.. ",
    r"^car ",
    # deprecations
    r"^findack ",
    r"^ack ",
]

compiled_ignore = [re.compile(i) for i in ignore]


def ignored(line):
    for pattern in compiled_ignore:
        if pattern.match(line):
            return True

    return False


def sensitive(line):
    for fragement in SENSITIVE_FRAGMENTS:
        if fragement.lower() in line.lower():
            return True

    return False


with open(history_file, "rb") as f:
    # strip lines and remove non utf-8 chars
    lines = [line.decode("utf-8", "ignore").strip() for line in f]


seen = set()
new_lines = list()

# note that reversed() does not copy lines, just results in reversed iteration
for line in reversed(lines):
    line = " ".join(line.split())  # remove multiple whitespace
    if not ignored(line) \
            and line not in seen \
            and not sensitive(line):
        new_lines.append(line)
        seen.add(line)

new_lines.reverse()

with tempfile.NamedTemporaryFile(mode="wb", dir=path.dirname(history_file), delete=False) as f:
    for line in new_lines:
        f.write((line + "\n").encode("utf-8"))

    tmpfname = f.name

# save atomically
rename(tmpfname, history_file)
