#!/usr/bin/python
import datetime
# run from vim in diary: :r! dates-daily

today = datetime.date.today()

for i in range(20):
    date = today + datetime.timedelta(days=i*7)
    print date.strftime('# %a %d %b %Y')
