#!/bin/bash
# run the best available terminal

# N.B. PATH may not include ~/.local/bin if launched from window manager

if [[ -x ~/.local/bin/alacritty ]]; then
    exec ~/.local/bin/alacritty "$@"
elif which kitty &> /dev/null; then
    exec kitty "$@"
elif which rxvt-unicode &> /dev/null; then
    exec rxvt-unicode "$@"
elif which xterm &> /dev/null; then
    exec xterm "$@"
elif which gnome-terminal &> /dev/null; then
    exec gnome-terminal "$@"
fi
