#!/bin/bash

function say {
    printf '\n\e[1;32m%s\e[m\n' "$*"
}


set -e

if [ -d ~/.password-store ]; then
    say "Password store"
    pass git pull --no-edit --commit origin master
    pass git push origin master
fi

if [ -d ~/.dstask ]; then
    say "dstask"
    dstask sync
fi

if [ -d ~/notes ]; then
    say "notes.git"
    ~/notes/sync
fi

if [ -d ~/dotfiles ]; then
    say "dotfiles"
    pushd ~/dotfiles
        git pull --no-edit --commit origin master
        ./4-user-configuration-naggie.sh
    popd
fi
