#!/bin/bash
if [ $# -eq 0 ]; then
    echo "Open files that contain given matches in vim-wrapper, selected by fzf"
    echo
    # arguments are given directly to ripgrep, so use its help page
    rg 2>&1 | sed "s+rg +rgfzf +g"
    exit 1
fi

# tty required, see GNU xargs man page
# Note that BSD args does not allow the delimiter to be \n so \0 must be used with the -0 option.
rg --smart-case --hidden --vimgrep --ignore-file=$HOME/.rgignore --color=always "$@" \
    | fzf --cycle --multi --ansi \
    | cut -d ':' -f 1-3 \
    | tr '\n' '\0' \
    | exec xargs -0 sh -c 'exec $0 "$@" </dev/tty' ~/.local/bin/vim-wrapper
