#!/usr/bin/env bash
# run the best available terminal

# N.B. PATH may not include ~/.local/bin if launched from window manager
export PATH=/usr/local/bin:/usr/bin/:~/.local/bin:$PATH

if which alacritty &> /dev/null; then
    # device pixel ratio scaling is annoying, disable
    # https://github.com/jwilm/alacritty/issues/1501
    WINIT_HIDPI_FACTOR=1.0 exec alacritty "$@"
elif which rxvt-unicode &> /dev/null; then
    exec rxvt-unicode "$@"
elif which xterm &> /dev/null; then
    exec xterm "$@"
elif which gnome-terminal &> /dev/null; then
    exec gnome-terminal "$@"
fi
